name: Deploy Production API

on:
  push:
    branches: [main]
    paths:
      - 'services/**'
      - 'scripts/**'
      - '.github/workflows/deploy-production.yml'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ENVIRONMENT: production

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Deploy United Tribes API
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh production
          
      - name: Run health checks
        run: |
          # Wait a moment for services to be ready
          sleep 30
          
          # Get service URLs from App Runner
          QUERY_SERVICE_URL=$(aws apprunner list-services \
            --query 'ServiceSummaryList[?ServiceName==`ut-query-service-production`].ServiceUrl' \
            --output text)
          
          if [ -n "$QUERY_SERVICE_URL" ]; then
            echo "Testing production API at: https://$QUERY_SERVICE_URL"
            
            # Test health endpoint
            curl -f "https://$QUERY_SERVICE_URL/health" || exit 1
            
            # Test basic query
            curl -f -X POST "https://$QUERY_SERVICE_URL/query" \
              -H "Content-Type: application/json" \
              -d '{"query": "test query", "k": 1}' || exit 1
              
            echo "✅ Production API health checks passed"
          else
            echo "❌ Could not find production query service URL"
            exit 1
          fi
          
      - name: Update deployment status
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Production deployment successful"
          else
            echo "❌ Production deployment failed"
            exit 1
          fi